### PR TITLE
product owner expects mp3s to work

### PR DESCRIPTION
**Pull request by atomical**

### CODE REVIEW

**Comment by cjcolvar** [comment]
I'm concerned that the mimetype is going to be incorrect for these skip transcoded audio items and that is going to lead to problems in the player since it gets stored on the derivative and passed on to the player.

**Comment by atomical** [comment]
profile.skip-transcoding-audio.http.mimetype = audio/ #{out.suffix}  ?

On Fri, Feb 14, 2014 at 10:42 AM, cjcolvar notifications@github.com wrote:

> I'm concerned that the mimetype is going to be incorrect for these skip
> transcoded audio items and that is going to lead to problems in the player
> since it gets stored on the derivative and passed on to the player.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/avalonmediasystem/avalon-felix/pull/8#issuecomment-35100660
> .

## 

website: http://adamhallett.com
cell: 815.793.1928

**Comment by cjcolvar** [comment]
This seems the easiest but I think we'd need to look at the mime types of the audio types supported for skip transcoding and see if this pattern would work.  Looks like this might not work after glancing at the main audio mime types: http://en.wikipedia.org/wiki/Internet_media_type#Type_audio

**Comment by cjcolvar** [comment]
I'll take a look at what the consequences of having a bad mime type are and if we can't correct it outside of Matterhorn.

**Comment by cjcolvar** [comment]
This seems to be ok.  We capture that mimetype and store it on the derivative and pass it along to the show view but it isn't actually used anywhere.  We should note somewhere that we have bad metadata though.

**Pull request merged**
